export default function PoliciesPage() {
 return <article className="section container policy-page">
  <span className="eyebrow">LEGAL</span>
  <h1>Policies</h1>
  <p className="policy-note">Last Updated: 08 October 2026</p>

  <section className="info-card"><h2>Privacy Policy</h2>
   <p>Muscle Worrior (“Muscle Worrior”, “we”, “us”, “our”) operates <b>www.muscleworrior.co.in</b> and is committed to protecting the privacy and security of information provided by customers and website visitors.</p>
   <h3>1. Information We Collect</h3><p>Depending on how you use our Website, we may collect full name, mobile number, email address, billing and shipping address, PIN code and city/state, order and purchase information, payment-related information necessary to process transactions, customer support communications, account/login information where applicable, website usage/device/browser information, IP address and approximate location information, cookies and similar technologies, and information voluntarily submitted through forms, reviews or enquiries.</p>
   <h3>2. How We Use Your Information</h3><p>We may process personal information for processing and delivering orders, confirming payments, customer support, returns/refunds/complaints, order and delivery updates, customer accounts, improving the Website/products/services, fraud prevention, legal and regulatory compliance, promotional communications where legally permitted, and maintaining business and transaction records.</p>
   <h3>3. Payments &amp; Sharing</h3><p>Payments may be processed through third-party payment providers. Muscle Worrior does not ordinarily store complete debit card, credit card or banking credentials on its own servers. Necessary information may be shared with delivery/logistics partners, payment processors, hosting and technology providers, customer support providers, accounting/legal/professional advisers, and authorities where legally required. We do not sell personal information as a commercial product.</p>
   <h3>4. Cookies, Security &amp; Retention</h3><p>Cookies may be used to keep the Website functioning, remember preferences, understand usage and measure marketing performance where applicable. Reasonable technical and organisational measures are used to protect information, but no online system can be guaranteed completely secure. Information is retained only as reasonably necessary for order fulfilment, customer service, accounting, legal, tax, regulatory and dispute-resolution requirements.</p>
   <h3>5. Your Rights, Children &amp; Third Parties</h3><p>Subject to applicable law, you may request information about processing, correction, deletion where legally applicable, withdrawal of consent, or raise a grievance. The Website is intended for customers legally permitted to purchase the products offered. Third-party websites, payment services and social platforms have their own privacy practices.</p>
   <h3>6. Contact / Privacy Grievance</h3><p><b>Muscle Worrior</b><br/>Website: www.muscleworrior.co.in<br/>Email: [PRIVACY/GRIEVANCE EMAIL]<br/>Phone: [PHONE NUMBER]<br/>Address: [REGISTERED/OFFICE ADDRESS]<br/>Grievance/Privacy Contact: [NAME/DESIGNATION]</p>
  </section>

  <section className="info-card"><h2>Refund, Return &amp; Cancellation Policy</h2>
   <p>Because our products include health supplements, nutrition products and other consumable products, we follow strict product-safety and hygiene standards.</p>
   <h3>1. General Return Policy</h3><p>For health, safety and hygiene reasons, products that have been opened, unsealed, consumed, used, tampered with or otherwise altered after delivery are generally not eligible for return or refund. Customers must inspect package and product condition promptly after delivery.</p>
   <h3>2. Non-Returnable / Non-Refundable Situations</h3><ul><li>Product opened, unsealed, used or partially consumed.</li><li>Packaging, seal, label or batch information tampered with.</li><li>Damage after delivery due to customer handling.</li><li>No reasonable proof of purchase/order details.</li><li>Change of mind after a correctly supplied product.</li><li>Wrong flavour, size, variant or product ordered.</li><li>Improper storage after delivery.</li><li>Return without prior approval.</li><li>Request outside the applicable return/complaint period.</li></ul>
   <h3>3. Damaged or Wrong Product</h3><p>If a package appears damaged, opened or tampered with, take clear photographs/videos before opening, record an unboxing video where reasonably possible, and contact Muscle Worrior promptly with the order number and evidence. For a wrong product, provide the order number, product photograph, shipping-label photograph and unboxing video where available. If verified, Muscle Worrior may arrange a replacement or other appropriate resolution.</p>
   <h3>4. Refunds &amp; Cancellation</h3><p>Where a refund is approved, it will generally be processed to the original payment method or another lawful method, subject to payment-provider timelines. Cancellation may be requested before dispatch; once dispatched, cancellation may not be possible. Promotional/discounted orders may have additional terms that do not override rights that cannot legally be excluded.</p>
   <h3>5. Contact</h3><p>Email: [CUSTOMER SUPPORT EMAIL]<br/>Phone/WhatsApp: [PHONE NUMBER]<br/>Include order number, customer name, registered mobile/email, product name, delivery date, reason and relevant photographs/videos.</p>
  </section>

  <section className="info-card"><h2>Shipping &amp; Delivery Policy</h2>
   <p>Muscle Worrior delivers nutrition and supplement products to serviceable locations across India through third-party logistics and courier partners.</p>
   <h3>1. Order Processing</h3><p>Orders are generally processed after successful payment confirmation. Processing time may vary depending on product availability, order volume, verification requirements and delivery location.</p>
   <h3>2. Delivery Time &amp; Delays</h3><p>Estimated delivery timelines displayed at checkout or communicated with the order are indicative and may vary because of courier delays, weather, public holidays, remote locations, operational disruptions, incorrect/incomplete addresses, or events beyond reasonable control.</p>
   <h3>3. Address, Delivery &amp; Package Inspection</h3><p>Customers are responsible for providing a complete and accurate delivery address, PIN code and contact number. Additional delivery charges may apply where re-shipping is required because of an incorrect or incomplete address. Customers should inspect the package at delivery and photograph/video any damage, opening or tampering.</p>
   <h3>4. Delivery Confirmation &amp; Contact</h3><p>Tracking information may be provided through email, SMS, WhatsApp or other available channels. Once a courier partner records delivery, a delivery dispute will be investigated using available logistics records.</p>
   <p>Email: [CUSTOMER SUPPORT EMAIL]<br/>Phone/WhatsApp: [PHONE NUMBER]</p>
  </section>

  <section className="info-card"><h2>Terms &amp; Conditions</h2>
   <p>Welcome to <b>www.muscleworrior.co.in</b>, operated by <b>[LEGAL COMPANY NAME]</b> (“Muscle Worrior”, “we”, “us”, “our”). By accessing or purchasing from the Website, you agree to these Terms &amp; Conditions.</p>
   <h3>1. Website Use</h3><p>You agree to use the Website only for lawful purposes and not to misuse, disrupt, damage or attempt unauthorised access to the Website or its systems.</p>
   <h3>2. Product Information</h3><p>We make reasonable efforts to keep product names, descriptions, images, prices and other information accurate. Packaging, colour, appearance and labelling may change. The physical product label is the primary source for ingredients, directions, warnings, allergen information, serving information and storage instructions.</p>
   <h3>3. Supplement Disclaimer</h3><p>Muscle Worrior products are not intended to diagnose, treat, cure or prevent disease unless expressly permitted and stated in accordance with applicable law. Customers should read the product label carefully before use. Customers with medical conditions, allergies, dietary restrictions, pregnancy-related concerns, or those taking medication should consult an appropriately qualified healthcare professional before using a supplement.</p>
   <h3>4. FSSAI &amp; Compliance</h3><p>Applicable products are intended to comply with applicable food-safety, health-supplement, labelling and packaging requirements. Where required, applicable FSSAI licence/registration details and product information will be displayed on the Website, packaging or invoice.</p>
   <h3>5. Pricing &amp; Orders</h3><p>Prices are subject to change without prior notice. Applicable taxes, shipping charges or other charges will be displayed where required. In case of an obvious pricing or technical error, Muscle Worrior may correct the error and, where appropriate, cancel the affected order and refund payment. Orders are requests to purchase and may be accepted, rejected or cancelled for product unavailability, pricing/technical errors, suspected fraud/misuse, incorrect information, delivery restrictions or regulatory/compliance requirements.</p>
   <h3>6. Intellectual Property &amp; User Content</h3><p>Website content including logos, text, graphics, product photographs, designs, branding and other materials may belong to Muscle Worrior or its licensors. Unauthorised copying, reproduction, modification or commercial use is prohibited except as permitted by law. If you submit reviews, photographs, comments or other content, you represent that you have the necessary rights and that it does not violate law or third-party rights. Muscle Worrior may moderate or remove unlawful, misleading, abusive, fraudulent or inappropriate content.</p>
   <h3>7. Third-Party Services, Limitation &amp; Governing Law</h3><p>The Website may use third-party payment gateways, courier services, analytics providers, hosting providers and other service providers. Their services may have their own terms. Nothing in these Terms is intended to exclude or restrict any liability, consumer right or remedy that cannot legally be excluded. These Terms are governed by the laws applicable in India and disputes are subject to competent courts/authorities having jurisdiction.</p>
   <h3>8. Contact</h3><p><b>Muscle Worrior</b><br/>Website: www.muscleworrior.co.in<br/>Email: [SUPPORT EMAIL]<br/>Phone: [PHONE NUMBER]<br/>Address: [REGISTERED/OFFICE ADDRESS]</p>
  </section>
 </article>;
}
